# -*- coding: utf-8 -*-
"""agent.py

Automatically generated by Colab.

"""

# Комментарии будут удалены после ознакомления вашего
# Я пишу это в Colab'е, но файлы будут у всех .py, чтобы легко было разрабатывать параллельно

# ----------------------------------------------------------------------------#
# LLM-engine Настройка
from langchain_google_genai import ChatGoogleGenerativeAI
llm = ChatGoogleGenerativeAI(
    model="gemini-2.5-flash",
    temperature=0.3,
    google_api_key='API-KEY' # потом сделаем из файла как просили, ключ у меня есть
)
# ----------------------------------------------------------------------------#
# Ноды агента Настройка
# испортирую функции из ваших будущих файло
from langchain.tools import Tool
tools = []

# Нод импорт пример
from Node_Test import func_test # если бы это была ваша часть: создаем Node_Test.py с функцией func_test https://github.com/mnedo/SMADIMO_GP3/tree/draft
tools.append(Tool(
    name="func_test",
    func=func_test,
    description="описание"))

# Ноды Role C
from Node_LoadData import load_data
tools.append(Tool(
    name="load_data",
    func=load_data,
    description="Загружает датасет из CSV-файла по переданному пути. "
                "Возвращает JSON со статусом, путём к сохранённому датафрейму, "
                "размерностью (rows, cols) и списком колонок."))

from Node_EDA import run_eda
tools.append(Tool(
    name="run_eda",
    func=run_eda,
    description="Проводит первичный анализ данных: типы колонок, пропуски, "
                "статистики, выявляет числовые/категориальные/текстовые признаки. "
                "Вызывать после load_data."))
# Ноды Role D
from Node_PreprocessDecision import preprocess_decision
tools.append(Tool(
    name="preprocess_decision",
    func=preprocess_decision,
    description="Анализирует EDA-отчёт и принимает решения по обработке: "
                "как заполнять пропуски, что делать с выбросами, нужна ли "
                "балансировка классов. Возвращает план действий в виде JSON."))

from Node_PreprocessExecution import preprocess_execution
tools.append(Tool(
    name="preprocess_execution",
    func=preprocess_execution,
    description="Выполняет план предобработки, сформированный preprocess_decision. "
                "Возвращает путь к очищенному датафрейму и список выполненных действий."))
# Ноды Role E
from Node_FeatureEngineering import feature_engineering
tools.append(Tool(
    name="feature_engineering",
    func=feature_engineering,
    description="Создаёт минимум 2 новых признака на основе существующих "
                "(отношения, бинаризация, извлечение из дат, агрегаты и т.д.). "
                "Возвращает обогащённый датафрейм и описание добавленных признаков."))

from Node_ModelSelection import model_selection
tools.append(Tool(
    name="model_selection",
    func=model_selection,
    description="На основе характеристик задачи (тип: классификация/регрессия, "
                "размер датасета, баланс классов) предлагает список релевантных "
                "моделей для обучения с обоснованием."))

from Node_TrainModels import train_models
tools.append(Tool(
    name="train_models",
    func=train_models,
    description="Обучает переданный список моделей на train-выборке, "
                "оценивает на test-выборке. Возвращает метрики по каждой модели "
                "и указывает лучшую."))

from Node_TuneHyperparams import tune_hyperparams
tools.append(Tool(
    name="tune_hyperparams",
    func=tune_hyperparams,
    description="Подбирает оптимальные гиперпараметры для выбранной модели "
                "с помощью Optuna. Возвращает лучшие параметры и улучшенную метрику. "
                "Вызывать после train_models для дополнительной оптимизации."))


# Ноды Role F
from Node_Memory import save_best_model, load_previous_best, compare_with_previous
tools.append(Tool(
    name="save_best_model",
    func=save_best_model,
    description="Сохраняет лучшую модель в .pkl и метрики в JSON для "
                "использования при следующих запусках агента."
))
tools.append(Tool(
    name="load_previous_best",
    func=load_previous_best,
    description="Загружает метрики и параметры лучшей модели из предыдущих "
                "запусков агента. Возвращает None, если это первый запуск."
))
tools.append(Tool(
    name="compare_with_previous",
    func=compare_with_previous,
    description="Сравнивает текущие метрики с сохранёнными из предыдущего "
                "запуска. Возвращает выводы: улучшение/ухудшение и насколько."
))




# ----------------------------------------------------------------------------#
memory = ConversationBufferMemory(memory_key="chat_history")
SYSTEM_PROMT = ''
agent = create_react_agent(llm, tools, prompt=SYSTEM_PROMT)
executor = AgentExecutor(agent=agent, tools=tools, memory=memory, verbose=True, handle_parsing_errors=True)

# Запуск
result = executor.invoke({"input": "Загрузи датасет и проведи полный pipeline"})