# -*- coding: utf-8 -*-
"""agent.py

Automatically generated by Colab.

"""
"""
Node_test.py — шаблон для создания Tool-функции агента.

Этот файл служит примером для всех Node_*.py в проекте.
Каждая нода реализует одну функцию-инструмент, которую агент вызывает
через LangChain.

Правила, которым должна следовать каждая функция-инструмент:
    1. Принимает строку (str) — LLM передаёт аргументы как строку.
       Если нужны структурированные аргументы — парсим JSON внутри.
    2. Всегда возвращает dict с ключом "status" ∈ {"ok", "error"}.
    3. Никогда не падает наружу — основная логика обёрнута в try/except.
    4. При ошибке возвращает {"status": "error", "error": "описание"}.
    5. Описание (docstring) важно — оно идёт в description тула для LLM.
"""

import json
from typing import Any


def func_test(input_str: str) -> dict[str, Any]:
    """
    Тестовая функция-заглушка. Принимает произвольную строку, возвращает
    её обратно в структурированном виде вместе со служебной информацией.

    Используется для проверки работоспособности агентского пайплайна.

    Args:
        input_str: произвольная строка от LLM. Может быть как простым
            текстом, так и JSON-строкой с параметрами.

    Returns:
        dict со структурой:
            {
                "status": "ok" | "error",
                "error": None | str,          # описание ошибки, если status="error"
                "received": str,              # то, что пришло на вход
                "parsed": dict | None,        # распарсенный JSON, если это был JSON
                "message": str                # человекочитаемый ответ
            }

    Example:
        >>> func_test("hello")
        {'status': 'ok', 'error': None, 'received': 'hello',
         'parsed': None, 'message': 'func_test получил строку: hello'}
    """
    try:
        # Попробуем распарсить как JSON — на случай, если LLM прислал структуру
        parsed = None
        try:
            parsed = json.loads(input_str)
        except (json.JSONDecodeError, TypeError):
            parsed = None

        return {
            "status": "ok",
            "error": None,
            "received": input_str,
            "parsed": parsed,
            "message": f"func_test получил строку: {input_str}"
        }

    except Exception as e:
        # Любая неожиданная ошибка — ловим и возвращаем структурированно,
        # чтобы агент не упал, а мог решить, что делать дальше.
        return {
            "status": "error",
            "error": f"{type(e).__name__}: {e}",
            "received": input_str,
            "parsed": None,
            "message": "func_test завершилась с ошибкой"
        }


# --- Локальный тест, чтобы роль могла проверить функцию без запуска всего агента ---
if __name__ == "__main__":
    # Простая строка
    print(func_test("hello world"))

    # JSON-строка
    print(func_test('{"dataset_path": "data/raw/sample.csv", "n_rows": 100}'))

    # Некорректный ввод (всё равно не падаем)
    print(func_test(""))